#!/usr/bin/env bun
/**
 * embed-assets.ts
 *
 * Build script that scans the Vite-built dist/ directory and generates
 * server/generated/embedded-assets.ts containing all frontend files
 * embedded as base64 strings.
 *
 * This allows the server to serve the frontend without requiring the
 * dist/ directory to be present at runtime (e.g., for binary distributions).
 *
 * Usage: bun run scripts/embed-assets.ts [dist-dir]
 */

import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'fs';
import { join, relative, extname } from 'path';

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
  '.map': 'application/json',
  '.txt': 'text/plain',
  '.xml': 'application/xml',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
};

function getMimeType(filePath: string): string {
  const ext = extname(filePath).toLowerCase();
  return MIME_TYPES[ext] ?? 'application/octet-stream';
}

function walkDir(dir: string): string[] {
  const files: string[] = [];

  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    // Directory doesn't exist or can't be read — skip
    return [];
  }

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...walkDir(fullPath));
    } else if (entry.isFile()) {
      files.push(fullPath);
    }
    // Symlinks and other types are ignored
  }

  return files;
}

function escapeJsString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

function generateEmbeddedAssets(distDir: string): string {
  const files = walkDir(distDir);
  files.sort(); // Deterministic order for reproducible builds

  const lines: string[] = [];

  for (const filePath of files) {
    const route = '/' + relative(distDir, filePath);
    const fileBytes = readFileSync(filePath);
    const base64 = fileBytes.toString('base64');
    const contentType = getMimeType(filePath);

    // Template literal backticks in base64 are extremely unlikely but we escape them
    const escapedBase64 = base64.replace(/`/g, '\\`').replace(/\${/g, '\\${');

    lines.push(`  addAsset("${escapeJsString(route)}", "${escapeJsString(contentType)}", \`${escapedBase64}\`);`);
  }

  return `// This file is auto-generated by scripts/embed-assets.ts
// Do not edit directly

export interface EmbeddedAsset {
  data: Buffer;
  contentType: string;
}

const embeddedAssets = new Map<string, EmbeddedAsset>();

// Each file embedded as base64
function addAsset(route: string, contentType: string, base64: string) {
  embeddedAssets.set(route, {
    data: Buffer.from(base64, 'base64'),
    contentType,
  });
}

${lines.join('\n')}

export default embeddedAssets;
`;
}

function main(): void {
  const distDir = process.argv[2] ?? join(process.cwd(), 'dist');
  const outputDir = join(process.cwd(), 'server', 'generated');
  const outputFile = join(outputDir, 'embedded-assets.ts');

  console.log(`[embed-assets] Scanning: ${distDir}`);

  mkdirSync(outputDir, { recursive: true });

  const content = generateEmbeddedAssets(distDir);

  writeFileSync(outputFile, content, 'utf-8');
  console.log(`[embed-assets] Generated: ${outputFile}`);

  const fileCount = content.match(/addAsset\(/g)?.length ?? 0;
  console.log(`[embed-assets] Embedded ${fileCount} files`);
}

main();
