#!/usr/bin/env bun
/**
 * embed-config.ts
 *
 * Build script that reads the .env file and generates
 * server/generated/embedded-config.ts containing all configuration
 * values embedded as a JavaScript object.
 *
 * This allows the binary to have default configuration built-in
 * without requiring an external .env file.
 *
 * Usage: bun run scripts/embed-config.ts [.env-file-path]
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

function parseEnvFile(content: string): Record<string, string> {
  const env: Record<string, string> = {};
  
  content.split('\n').forEach(line => {
    const trimmedLine = line.trim();
    if (trimmedLine && !trimmedLine.startsWith('#')) {
      const eqIndex = trimmedLine.indexOf('=');
      if (eqIndex > 0) {
        const key = trimmedLine.slice(0, eqIndex).trim();
        const value = trimmedLine.slice(eqIndex + 1).trim();
        if (key) {
          env[key] = value;
        }
      }
    }
  });
  
  return env;
}

function generateEmbeddedConfig(envPath: string): string {
  let envVars: Record<string, string> = {};
  
  if (existsSync(envPath)) {
    const content = readFileSync(envPath, 'utf8');
    envVars = parseEnvFile(content);
    console.log(`[embed-config] Loaded ${Object.keys(envVars).length} variables from ${envPath}`);
  } else {
    console.log(`[embed-config] Warning: ${envPath} not found, using empty config`);
  }

  const configEntries = Object.entries(envVars)
    .map(([key, value]) => `  "${escapeString(key)}": "${escapeString(value)}"`)
    .join(',\n');

  return `// This file is auto-generated by scripts/embed-config.ts
// Do not edit directly

/**
 * Embedded configuration values baked into the binary at build time.
 * These serve as defaults and can be overridden by:
 * 1. Environment variables
 * 2. ~/.hoocowork/.env file
 * 3. CLI arguments
 */
export const embeddedConfig: Record<string, string> = {
${configEntries}
};

/**
 * Apply embedded configuration to process.env.
 * Only sets values that are not already defined.
 */
export function applyEmbeddedConfig(): void {
  for (const [key, value] of Object.entries(embeddedConfig)) {
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

export default embeddedConfig;
`;
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

function main(): void {
  const envPath = process.argv[2] ?? join(process.cwd(), '.env');
  const outputDir = join(process.cwd(), 'server', 'generated');
  const outputFile = join(outputDir, 'embedded-config.ts');

  console.log(`[embed-config] Reading: ${envPath}`);

  const content = generateEmbeddedConfig(envPath);

  writeFileSync(outputFile, content, 'utf-8');
  console.log(`[embed-config] Generated: ${outputFile}`);
}

main();
